# Generated by Django 4.2.4 on 2023-08-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
